pvp_world: world
lobby:

ffa_tag: ffa_player
fight_time: 15
fight_message: "§c§l%sec%초 후 전투가 종료됩니다"
fight_end_message: "§c§l전투가 종료되었습니다"
blocked_commands_during-fight:
  - /lobby
  - /pvpworld:lobby
  - /kit
  - /pvpworld:kit

allowed_commands_in_pvp_world:
  - /lobby
  - /ffa
  - /duel
  - /party
  - /leave
  - /w
  - /pvpworld:lobby
  - /pvpworld:ffa
  - /pvpworld:duel
  - /pvpworld:party
  - /pvpworld:leave
  - /minecraft:w