name: PvpWorld
version: ${project.version}
main: me.ujun.pvpWorld.PvpWorld
api-version: '1.21'
author: U_jun
softdepend: [WorldEdit, FastAsyncWorldEdit]
commands:
  lobby:
    permission: pvpworld.lobby
  ffa:
    permission: pvpworld.ffa
  duel:
    permission: pvpworld.duel
  party:
    permission: pvpworld.party
  duelwatch:
    permission: pvpworld.duelwatch
  leave:
    permission: pvpworld.leave
  forceduel:
    permission: pvpworld.admin
    usage: /forceduel <player> <kit> <round>
  pvpworld:
    permission: pvpworld.admin
    usage: /pvpworld <subcommand>

permissions:
  pvpworld.admin:
    default: op
  pvpworld.ffa:
    default: true
  pvpworld.duel:
    default: true
  pvpworld.party:
    default: true
  pvpworld.lobby:
    default: true
  pvpworld.duelwatch:
    default: true
  pvpworld.leave:
    default: true
